version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: jobscr_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data

  worker:
    build:
      context: .
      dockerfile: infra/Dockerfile-worker
    container_name: jobscr_worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data