# infra/Dockerfile-worker
FROM python:3.11-slim

WORKDIR /worker
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y build-essential libxml2-dev libxslt-dev git curl

COPY backend/requirements.txt /worker/requirements.txt
RUN pip install --upgrade pip && pip install -r /worker/requirements.txt

COPY backend /worker/backend
COPY infra /worker/infra

CMD ["python", "infra/oc_worker.py"]
